#Battery config -------------------
#CONFIG_ZMK_BATTERY_REPORTING=y
#CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
#CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=7200000

##for NiMH battery
CONFIG_ZMK_NON_LIPO_BATTERY_MANAGEMENT=y

# optional
CONFIG_ZMK_NON_LIPO_MAX_MV=1360
CONFIG_ZMK_NON_LIPO_MIN_MV=1020
CONFIG_ZMK_NON_LIPO_LOW_MV=1000
#CONFIG_ZMK_NON_LIPO_ADV_SLEEP_TIMEOUT=60000
# 60 seconds


# ========================================
# DYA Studio 用の設定（Peripheral 側）
# ========================================
# バッテリー履歴（Peripheral 側）RELAY
#CONFIG_ZMK_BATTERY_HISTORY=n

# Settings RPC（Peripheral 側）
CONFIG_ZMK_SETTINGS_RPC=y

# Split イベントリレー（Peripheral 側）
CONFIG_ZMK_SPLIT_RELAY_EVENT=y

# 設定の永続化
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000

# ヒープメモリの拡張
CONFIG_HEAP_MEM_POOL_SIZE=32768

# Bluetooth (Zephyr BLE stack) Memory / Buffer Tuning
CONFIG_BT_RX_STACK_SIZE=2560
CONFIG_BT_HCI_TX_STACK_SIZE=768

# # キースキャン診断機能の有効化
# CONFIG_ZMK_KSCAN_DIAGNOSTICS=y
# # 分割キーボードの子機（Peripheral）側の診断応答を有効化 
# CONFIG_ZMK_KSCAN_DIAGNOSTICS_SPLIT=y
# # 子機のマトリクス・トポロジー情報を送信するための中継バッファサイズ拡張（左右両方に必須）
# CONFIG_ZMK_SPLIT_RELAY_EVENT_DATA_LEN=256

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_ZMK_CUSTOM_SETTINGS=y
CONFIG_ZMK_CUSTOM_SETTINGS_SPLIT_RPC_RELAY=y
CONFIG_ZMK_SPLIT_RELAY_EVENT_DATA_LEN=240

CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=768
CONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=6144
CONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=384
CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=384
CONFIG_ZMK_STUDIO_RPC_CUSTOM_SUBSYSTEM_REQUEST_PAYLOAD_MAX_BYTES=256
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=6144
CONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=6000
CONFIG_ZMK_CUSTOM_SETTINGS_LARGE_VALUE_MAX_SIZE=256

CONFIG_ZMK_WATCHDOG=y
